// <auto-generated />
namespace Implementation.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_Column_RequestJob_LastCompletedDateTime_To_NonNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_Column_RequestJob_LastCompletedDateTime_To_NonNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701042147030_Change_Column_RequestJob_LastCompletedDateTime_To_NonNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
